// using the if-statement
#include <iostream>
using std::cout;
using std::endl;
using std::cin;

int main()
{
	char ch;
	int spaces = 0;
	int total = 0;
	cin.get(ch);
	while (ch != '.') // quit at the end of the sentence
	{
		if (ch == ' ') // check if ch is a space
		    ++spaces;
		 ++total;      // done every time
		 cin.get(ch);
	}
	cout << spaces << " spaces, " << total;
	cout << " characters total in sentence\n";
	return 0;
}
/*Note that the total count includes the newline character that is generated by press-
ing Enter.*/
